### PR TITLE
Fixes so that one branch builds on both android + linux.

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by metajack** [comment]
What is -avoid-version needed for?

**Comment by glennw** [comment]
Somewhere deep in the NDK build scripts (in the android SDK, not our scripts) it appears to only copy .so files into the package. So without avoid-version, our code references libfontconfig.so.1.8.0 which then fails to load as it's not present. I copied this hack from our android branch - is there a better way to work around that?

**Comment by metajack** [comment]
I was mostly curious. It seemed benign.

**Pull request merged**
